# Generated by Django 3.2.13 on 2022-04-17 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_chatline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatline',
            name='sayer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.player'),
        ),
    ]
