# Generated by Django 3.2.13 on 2022-04-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_chatline_sayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='x',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='y',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
