# Generated by Django 3.2.13 on 2022-04-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220417_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avatar',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='x',
            field=models.PositiveIntegerField(default=45),
        ),
        migrations.AlterField(
            model_name='player',
            name='y',
            field=models.PositiveIntegerField(default=42),
        ),
    ]
