# Generated by Django 3.2.13 on 2022-04-25 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220424_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='last_interacted_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='player',
            name='logged_in',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='x',
            field=models.PositiveIntegerField(default=530),
        ),
        migrations.AlterField(
            model_name='player',
            name='y',
            field=models.PositiveIntegerField(default=540),
        ),
    ]
